const ERROR_BADREQUEST = 400;
const ERROR_UNAUTORIZED = 401;
const ERROR_FORBIDDEN = 403;
const ERROR_NOTFOUND = 404;
const ERROR_CONFLICT = 409;
const ERROR_SERVER = 500;

module.exports = {
  ERROR_BADREQUEST,
  ERROR_UNAUTORIZED,
  ERROR_FORBIDDEN,
  ERROR_NOTFOUND,
  ERROR_CONFLICT,
  ERROR_SERVER,
};
